//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;
using vJoyInterfaceWrap;

namespace OnScreenController
{
    public class MappingData
    {
        public string Name
        {
            get;
            set;
        }
        public uint Code
        {
            get;
            set;
        }
        public MappingData(string name, uint code)
        {
            Name = name;
            Code = code;
        }
    }

    class VirtualMappingData
    {
        //Data from https://docs.microsoft.com/en-us/uwp/api/windows.system.virtualkey?view=winrt-19041
        static public MappingData[] mComboToKeycodeMapping = new MappingData[] 
        {
            new MappingData("None",0),
            new MappingData("A",65),
            //new MappingData("Accept",30),
            new MappingData("Add",107),
            //new MappingData("Application",93),
            new MappingData("B",66),
            new MappingData("Back",8),
            new MappingData("C",67),
            //new MappingData("Cancel",3),
            new MappingData("CapitalLock",20),
            //new MappingData("Clear",12),
            new MappingData("Control",17),
            //new MappingData("Convert",28),
            new MappingData("D",68),
            new MappingData("Decimal",110),
            new MappingData("Delete",46),
            new MappingData("Divide",111),
            new MappingData("Down",40),
            new MappingData("E",69),
            new MappingData("End",35),
            new MappingData("Enter",13),
            new MappingData("Escape",27),
            //new MappingData("Execute",43),
            new MappingData("F",70),
            new MappingData("F1",112),
            new MappingData("F10",121),
            new MappingData("F11",122),
            new MappingData("F12",123),
            //new MappingData("F13",124),
            //new MappingData("F14",125),
            //new MappingData("F15",126),
            //new MappingData("F16",127),
            //new MappingData("F17",128),
            //new MappingData("F18",129),
            //new MappingData("F19",130),
            new MappingData("F2",113),
            //new MappingData("F20",131),
            //new MappingData("F21",132),
            //new MappingData("F22",133),
            //new MappingData("F23",134),
            //new MappingData("F24",135),
            new MappingData("F3",114),
            new MappingData("F4",115),
            new MappingData("F5",116),
            new MappingData("F6",117),
            new MappingData("F7",118),
            new MappingData("F8",119),
            new MappingData("F9",120),
            //new MappingData("Favorites",171),
            //new MappingData("Final",24),
            new MappingData("G",71),
            //new MappingData("GamepadA",195),
            //new MappingData("GamepadB",196),
            //new MappingData("GamepadDPadDown",204),
            //new MappingData("GamepadDPadLeft",205),
            //new MappingData("GamepadDPadRight",206),
            //new MappingData("GamepadDPadUp",203),
            //new MappingData("GamepadLeftShoulder",200),
            //new MappingData("GamepadLeftThumbstickButton",209),
            //new MappingData("GamepadLeftThumbstickDown",212),
            //new MappingData("GamepadLeftThumbstickLeft",214),
            //new MappingData("GamepadLeftThumbstickRight",213),
            //new MappingData("GamepadLeftThumbstickUp",211),
            //new MappingData("GamepadLeftTrigger",201),
            //new MappingData("GamepadMenu",207),
            //new MappingData("GamepadRightShoulder",199),
            //new MappingData("GamepadRightThumbstickButton",210),
            //new MappingData("GamepadRightThumbstickDown",216),
            //new MappingData("GamepadRightThumbstickLeft",218),
            //new MappingData("GamepadRightThumbstickRight",217),
            //new MappingData("GamepadRightThumbstickUp",215),
            //new MappingData("GamepadRightTrigger",202),
            //new MappingData("GamepadView",208),
            //new MappingData("GamepadX",197),
            //new MappingData("GamepadY",198),
            //new MappingData("GoBack",166),
            //new MappingData("GoForward",167),
            //new MappingData("GoHome",172),
            new MappingData("H",72),
            //new MappingData("Hangul",21),
            //new MappingData("Hanja",25),
            //new MappingData("Help",47),
            new MappingData("Home",36),
            new MappingData("I",73),
            //new MappingData("ImeOff",26),
            //new MappingData("ImeOn",22),
            new MappingData("Insert",45),
            new MappingData("J",74),
            //new MappingData("Junja",23),
            new MappingData("K",75),
            //new MappingData("Kana",21),
            //new MappingData("Kanji",25,
            new MappingData("L",76),
            new MappingData("Left",37),
            //new MappingData("LeftButton",1),
            new MappingData("LeftControl",162),
            new MappingData("LeftMenu",164),
            new MappingData("LeftShift",160),
            new MappingData("LeftWindows",91),
            new MappingData("M",77),
            new MappingData("Menu",18),
            //new MappingData("MiddleButton",4),
            //new MappingData("ModeChange",31),
            new MappingData("Multiply",106),
            new MappingData("N",78),
            //new MappingData("NavigationAccept",142),
            //new MappingData("NavigationCancel",143),
            //new MappingData("NavigationDown",139),
            //new MappingData("NavigationLeft",140),
            //new MappingData("NavigationMenu",137),
            //new MappingData("NavigationRight",141),
            //new MappingData("NavigationUp",138),
            //new MappingData("NavigationView",136),
            //new MappingData("NonConvert",29),
            new MappingData("Number0",48),
            new MappingData("Number1",49),
            new MappingData("Number2",50),
            new MappingData("Number3",51),
            new MappingData("Number4",52),
            new MappingData("Number5",53),
            new MappingData("Number6",54),
            new MappingData("Number7",55),
            new MappingData("Number8",56),
            new MappingData("Number9",57),
            new MappingData("NumberKeyLock",144),
            new MappingData("NumberPad0",96),
            new MappingData("NumberPad1",97),
            new MappingData("NumberPad2",98),
            new MappingData("NumberPad3",99),
            new MappingData("NumberPad4",100),
            new MappingData("NumberPad5",101),
            new MappingData("NumberPad6",102),
            new MappingData("NumberPad7",103),
            new MappingData("NumberPad8",104),
            new MappingData("NumberPad9",105),
            new MappingData("O",79),
            new MappingData("P",80),
            new MappingData("PageDown",34),
            new MappingData("PageUp",33),
            new MappingData("Pause",19),
            new MappingData("Print",42),
            new MappingData("Q",81),
            new MappingData("R",82),
            //new MappingData("Refresh",168),
            new MappingData("Right",39),
            //new MappingData("RightButton",2),
            new MappingData("RightControl",163),
            new MappingData("RightMenu",165),
            new MappingData("RightShift",161),
            new MappingData("RightWindows",92),
            new MappingData("S",83),
            //new MappingData("Scroll",145),
            //new MappingData("Search",170),
            //new MappingData("Select",41),
            new MappingData("Separator",108),
            new MappingData("Shift",16),
            //new MappingData("Sleep",95),
            //new MappingData("Snapshot",44),
            new MappingData("Space",32),
            //new MappingData("Stop",169),
            new MappingData("Subtract",109),
            new MappingData("T",84),
            new MappingData("Tab",9),
            new MappingData("U",85),
            new MappingData("Up",38),
            new MappingData("V",86),
            new MappingData("W",87),
            new MappingData("X",88),
            //new MappingData("XButton1",5),
            //new MappingData("XButton2",6),
            new MappingData("Y",89),
            new MappingData("Z",90)
        };

        static public MappingData[] mComboToJoystickButtonMapping = new MappingData[]
        {
            new MappingData("None", 0),
            new MappingData("Button1",1),
            new MappingData("Button2",2),
            new MappingData("Button3",3),
            new MappingData("Button4",4),
            new MappingData("Button5",5),
            new MappingData("Button6",6),
            new MappingData("Button7",7),
            new MappingData("Button8",8),
            new MappingData("Button9",9),
            new MappingData("Button10",10),
            new MappingData("Button11",11),
            new MappingData("Button12",12),
            new MappingData("Button13",13),
            new MappingData("Button14",14),
            new MappingData("Button15",15),
            new MappingData("Button16",16),
            new MappingData("Button17",17),
            new MappingData("Button18",18),
            new MappingData("Button19",19),
            new MappingData("Button20",20),
            new MappingData("Button21",21),
            new MappingData("Button22",22),
            new MappingData("Button23",23),
            new MappingData("Button24",24),
            new MappingData("Button25",25),
            new MappingData("Button26",26),
            new MappingData("Button27",27),
            new MappingData("Button28",28),
            new MappingData("Button29",29),
            new MappingData("Button30",30),
            new MappingData("Button31",31),
            new MappingData("Button32",32),
            new MappingData("Button33",33),
            new MappingData("Button34",34),
            new MappingData("Button35",35),
            new MappingData("Button36",36),
            new MappingData("Button37",37),
            new MappingData("Button38",38),
            new MappingData("Button39",39),
            new MappingData("Button40",40),
            new MappingData("Button41",41),
            new MappingData("Button42",42),
            new MappingData("Button43",43),
            new MappingData("Button44",44),
            new MappingData("Button45",45),
            new MappingData("Button46",46),
            new MappingData("Button47",47),
            new MappingData("Button48",48),
            new MappingData("Button49",49),
            new MappingData("Button50",50),
            new MappingData("Button51",51),
            new MappingData("Button52",52),
            new MappingData("Button53",53),
            new MappingData("Button54",54),
            new MappingData("Button55",55),
            new MappingData("Button56",56),
            new MappingData("Button57",57),
            new MappingData("Button58",58),
            new MappingData("Button59",59),
            new MappingData("Button60",60),
            new MappingData("Button61",61),
            new MappingData("Button62",62),
            new MappingData("Button63",63),
            new MappingData("Button64",64),
            new MappingData("Button65",65),
            new MappingData("Button66",66),
            new MappingData("Button67",67),
            new MappingData("Button68",68),
            new MappingData("Button69",69),
            new MappingData("Button70",70),
            new MappingData("Button71",71),
            new MappingData("Button72",72),
            new MappingData("Button73",73),
            new MappingData("Button74",74),
            new MappingData("Button75",75),
            new MappingData("Button76",76),
            new MappingData("Button77",77),
            new MappingData("Button78",78),
            new MappingData("Button79",79),
            new MappingData("Button80",80),
            new MappingData("Button81",81),
            new MappingData("Button82",82),
            new MappingData("Button83",83),
            new MappingData("Button84",84),
            new MappingData("Button85",85),
            new MappingData("Button86",86),
            new MappingData("Button87",87),
            new MappingData("Button88",88),
            new MappingData("Button89",89),
            new MappingData("Button90",90),
            new MappingData("Button91",91),
            new MappingData("Button92",92),
            new MappingData("Button93",93),
            new MappingData("Button94",94),
            new MappingData("Button95",95),
            new MappingData("Button96",96),
            new MappingData("Button97",97),
            new MappingData("Button98",98),
            new MappingData("Button99",99),
            new MappingData("Button100",100)
        };

        static public MappingData[] mComboToJoystickAxisMapping = new MappingData[]
        {
            new MappingData("None", (uint)0),
            new MappingData("AXIS 1", (uint) HID_USAGES.HID_USAGE_X),
            new MappingData("AXIS 2", (uint) HID_USAGES.HID_USAGE_Y),
            new MappingData("AXIS 3", (uint) HID_USAGES.HID_USAGE_Z),
            new MappingData("AXIS 4", (uint) HID_USAGES.HID_USAGE_RX),
            new MappingData("AXIS 5", (uint) HID_USAGES.HID_USAGE_RY),
            new MappingData("AXIS 6", (uint) HID_USAGES.HID_USAGE_RZ),
            new MappingData("AXIS 7", (uint) HID_USAGES.HID_USAGE_SL0),
            new MappingData("AXIS 8", (uint) HID_USAGES.HID_USAGE_SL1)
        };

        static public MappingData[] mComboToMouseAxisMapping = new MappingData[]
        {
            new MappingData("None", (uint)0),
            new MappingData("Mouse X", (uint)1),
            new MappingData("Mouse Y", (uint)2)
        };

        static public MappingData[] mComboToInputMapping = new MappingData[]
        {
            new MappingData("Joystick", (uint)0),
            new MappingData("Keyboard", (uint)1)
        };

        static public MappingData[] mComboToOptionMapping = new MappingData[]
        {
            new MappingData("Press", (uint)0),
            new MappingData("Release", (uint)1),
            new MappingData("Click", (uint)2),
            new MappingData("Toggle", (uint)3)
        };
    }
}
